### ISSUE TITLE
Lustre LSoM support?

### ISSUE THREAD

**Issue by cfaberddn** [DDNeu/fs-scan#2]
Hi,

Does this tool support Lustre's LSoM (Lazy Size on Metadata) feature available through statx() syscall?

Thanks!

**Comment by alexandrestein** [comment]
Hi,

Currently it's a simple/regular file stat call.
It is platform agnostic. 

Would you like to see LSoM implemented in future ?

**Comment by cfaberddn** [comment]
Hi Alexandre,

It's an exclusive linux kernel feature, and LSoM is exclusive to Lustre (though there may be similar extended stat arguments which are available for other networked file systems. 

In the case of lustre, if this were implemented, I would be surprised if you didn't get double the performance or better. However the caveat being that the size represented may not be fully accurate in all cases.

**Comment by alexandrestein** [comment]
This package was developed to be run from anywhere with limited requirement (no MPI and dependencies) but with reasonable performances.

If the precision is less relevant than the time spend to check I can try (when I have time) to use this [lib](https://docs.rs/statx-sys/latest/statx_sys/index.html) to access statx() attribute. 
If I'm correct, this is the way to get the info from the application. Right?

**Comment by cfaberddn** [comment]
Hi Yes, this is correct.

**Comment by alexandrestein** [comment]
So, I just need to:

- [ ] learn how to use this C lib from Rust
- [x] add some parameters flag
    - [x] nb-threads
    - [ ] lustre-lsom
- [ ] do a check on the first iteration if lustre-lsom flag is set
If LSoM is available it can work with it otherwise (because not lustre or kernel is too old) stick to the standard stats.

Would it be a better app for you? 


**PS: this comment will be used to track progress**

**Comment by cfaberddn** [comment]
Hi,
Yes. As I mentioned before. I believe such a change would (if selected) allow for a massive performance improvement of this application when doing scans as it avoids the client having to reach out to the object stores to calculate actual object size, rather it talks directly to the metadata target for the "lazy" size that the metadata server should have. If this is not present, a fallback to stat() should be done to ensure size is still calculated.

**Comment by alexandrestein** [comment]
I totally get the point. 
As of today it triggers RPCs to probably every MDS/OSS (depending of the scope)
Using LSoM would greatly reduce the load on the OSS.

My question is, can you elaborate on the level of uncertainty? 
If I try to catch very small files to design the DoM ratio and/or PFL. 
What can be the gap between the reality and the report?

**Comment by cfaberddn** [comment]
The uncertainty is introduced due the fact that you can have multiple client / writers working on a file concurrently, if one of those writers closes the file early (while the rest continue to operate) the size value is calculated based on what the actual object sizes are. As the remaining writers close the file, this value is updated to be the correct / actual value of the file size. The uncertainty is introduced when some of those writers are evicted or the object store itself crashes and recovers. During recovery this value is not updated and the older (now stale) value is still present.

As soon as the file in question is opened and closed (it can literally be a simple open -> close), the object stores will automatically update the size value to represent the actual value of the file.

So for most operations and nearly all files the value should be accurate, with the exception noted above.

Does this make sense?

**Comment by alexandrestein** [comment]
Totally, thanks. :smiley: 
I keep the issue open. No commitment on the ETA but this feature make total sense.

Thank you.

Out of curiosity:

- Did you tried it on a big system? 
- What was the time needed?

**Comment by cfaberddn** [comment]
Not yet, however we do have a customer interested in using this tool with multiple directory trees with files in excess of 200 million files. 
The current 'lfs find' and POSIX 'find' tools reportedly take somewhere in the neighborhood of 10 hours or more to preform the scan (which is linear, not parallel like this tool) so I imagine even without this feature a significant speedup will be achieved.

Thanks!

**Comment by alexandrestein** [comment]
Very good. I'm confident you should have a significative speedup.
I would appropriate to have your feedback after the run if possible. 

FYI: The tool runs in parallel 4 times the number of logical CPU. 
Depending on the node you will run it, the gain may vary. 

Cheers,
Alex

**Comment by cfaberddn** [comment]
Thanks Alex! I'll keep an eye on this project for when you have a chance to add this feature. 

Cheers!

-cf

**Comment by alexandrestein** [comment]
Just to keep the libs somewhere near to the issue.
Raphael (French DDN colleague) found much more suitable lib to try that functionality. 

- https://github.com/bytecodealliance/rustix
- https://github.com/SUPERCILEX/fuc/blob/15fa3a7c3675717d5d17251b1d6afec8c6871715/fuc_engine/src/ops/mod.rs#L68-L83

Work still in progress.
